print("Welcome to the tip calculator.")
bill = float(input("What was the total bill? $"))
percentage = input("What percentage tip would you like to give? 10, 12, or 15? ")
percentage = float("1." + percentage)
num_people = float(input("How many people to split the bill? "))
summary = round((bill/num_people)*percentage,2)
print(f"Each person should pay: ${summary}")